### ISSUE TITLE
Capture user input

### ISSUE THREAD

**Issue by christinedbaxter** [baxters4karma/readme-generator#1]
***Description***
- Capture user input with command-line arguments

***Tasks***

- [x] Set up project repository, clone, and create feature
- [x] Use command line to provide input data to application, making code dynamic
- [x] Print dynamic output by creating a function that accepts command-line arguments and prints to console
- [x] Save progress with Git
