### ISSUE TITLE
Modify template to handle more data

### ISSUE THREAD

**Issue by christinedbaxter** [baxters4karma/readme-generator#4]
***Description***
- Expand template to account for more project data
- Modify template to account for multiple projects

***Tasks***

- [x] Update template function input to accept the Inquirer response object as a parameter then separate data by what section of the page it will be written to
- [x] Create the Title and Questions section
- [x] Create the Table of Contents section
- [x] Create the project sections
- [x] Add license badge
