### ISSUE TITLE
Generate file

### ISSUE THREAD

**Issue by christinedbaxter** [baxters4karma/readme-generator#5]
***Description***
- Output user input to a file

***Tasks***

- [x] Finalize output style
- [x] Write file using Promises
- [x] Export functions and wrap
- [x] Save progress with Git
